services:
  yt-down:
    image: ghcr.io/iankulin/yt-down
    ports:
      - '3001:3001'
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
    restart: unless-stopped
    container_name: yt-down
    environment:
      # Set logging level - valid values: silent, error, warn, info, debug
      LOG_LEVEL: debug
